<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_50";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
            //hem d'afegir els nostres inserts
 
                    // Inserts for Credentials entity    
                    "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                    "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob2', 'sob2')",
                    "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob3', 'sob3')",
                    "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob4', 'sob4')",
                    "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob5', 'sob5')",

                
                    // Inserts for GameType entity
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'ExcitingGame')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'ThrillingGame')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'AwesomeAdventure')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'ExcitingChallenge')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'ImmersiveStoryline')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'EpicQuest')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'ExcitingAdventure')",
                    "INSERT INTO " + schema + ".GAMETYPE (ID, TYPE) VALUES (NEXT VALUE FOR GAMETYPE_GEN, 'FantasticExperience')",

                    // Inserts for Customer entity
                    "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'jon@example.com', 1)",
                    "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'alice@example.com', 2)",
                    "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'bob@example.com', 5)",
                    "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'charlie@example.com', 3)",
                    "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'diana@example.com', 4)",

                    // Inserts for Rent entity
                    "INSERT INTO " + schema + ".RENT (ID, RETURNDATE, CUSTOMER_ID) VALUES (NEXT VALUE FOR RENT_GEN, '2023-11-21 20:30:15', 1)",
                    "INSERT INTO " + schema + ".RENT (ID, RETURNDATE, CUSTOMER_ID) VALUES (NEXT VALUE FOR RENT_GEN, '2020-08-11 10:00:30', 2)",
                    "INSERT INTO " + schema + ".RENT (ID, RETURNDATE, CUSTOMER_ID) VALUES (NEXT VALUE FOR RENT_GEN, '2023-02-09 05:48:55', 3)",
                    "INSERT INTO " + schema + ".RENT (ID, RETURNDATE, CUSTOMER_ID) VALUES (NEXT VALUE FOR RENT_GEN, '2024-06-25 12:30:00', 4)",
                    "INSERT INTO " + schema + ".RENT (ID, RETURNDATE, CUSTOMER_ID) VALUES (NEXT VALUE FOR RENT_GEN, '2023-12-14 17:22:26', 5)",

                    // Inserts for Console entity
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'PlayStation5')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'NINTENDODS')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'XBOX')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'GAMEBOY')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'GAMEBOYADVANCE')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'GAMEBOYCOLOR')",
                    "INSERT INTO " + schema + ".CONSOLE (ID, CONSOLE) VALUES (NEXT VALUE FOR CONSOLE_GEN, 'NINTENDO3DS')",


                   // Inserts for Shop entity
                    "INSERT INTO " + schema + ".SHOP (ID, NAME, ADDRESS) VALUES (NEXT VALUE FOR SHOP_GEN, 'GameHaven', '123 Main Street')",
                    "INSERT INTO " + schema + ".SHOP (ID, NAME, ADDRESS) VALUES (NEXT VALUE FOR SHOP_GEN, 'PlayGround', '456 Oak Avenue')",
                    "INSERT INTO " + schema + ".SHOP (ID, NAME, ADDRESS) VALUES (NEXT VALUE FOR SHOP_GEN, 'Pixel Palace', '789 Elm Blvd')",
                    "INSERT INTO " + schema + ".SHOP (ID, NAME, ADDRESS) VALUES (NEXT VALUE FOR SHOP_GEN, 'Gamers Den', '101 Pine Lane')",
                    "INSERT INTO " + schema + ".SHOP (ID, NAME, ADDRESS) VALUES (NEXT VALUE FOR SHOP_GEN, 'Arcade Alley', '202 Cedar Road')",
                
                    // Inserts for Videogame entity
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'DonkeyKong', 1, 10.0, 'Barrel-Busting Arcade Classic', 4, 8)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'DrMario', 0, 15.0, 'Virus-Vanquishing Puzzle Quest', 5, 3)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'GameWatch', 1, 30.0, 'Timeless Portable Gaming Delight', 6, 5)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'MarioKartDS', 1, 15.0, 'Kart-Racing Fun On-the-Go', 2, 7)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'SuperMarioLand', 0, 25.0, 'Platforming Magic in Your Hands', 4, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'MarioPartyDS', 1, 20.0, 'Mini-Game Madness on Dual Screens', 2, 2)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'Minecraft', 1, 18.0, 'Infinite Creativity and Exploration', 7, 4)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'MonstersINC', 1, 12.0, 'Monstrously Fun Adventure', 5, 3)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'NamComMuseum', 0, 22.0, 'Nostalgic Journey through Arcade History', 5, 3)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'Spiderman', 0, 22.0, 'Web-Slinging Action-Packed Adventure', 2, 3)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'SonicGenerations', 1, 15.0, 'Speedy Hedgehogs Time-Bending Quest', 7, 2)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'SuperMarioAdvanced', 1, 20.0, 'Classic Plumbers Side-Scrolling Adventure', 5, 2)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'SuperMarioBros', 1, 30.0, 'Legendary Mushroom Kingdom Odyssey', 2, 5)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'Tetris', 0, 15.0, 'Timeless Block-Stacking Challenge', 4, 3)",
                    "INSERT INTO " + schema + ".VIDEOGAME (ID, NAME, AVAILABLE, PRICERENT, DESCRIPTION, CONSOLE_ID, TYPE_ID) VALUES (NEXT VALUE FOR VIDEOGAME_GEN, 'TomJerry', 1, 10.0, 'Whacky Cat-and-Mouse Gaming Thrill', 6, 8)",            

                    // Inserts for Videogame-Shop relationship
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 5, 1, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 2, 2, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 10, 3, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 3, 4, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 8, 5, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 2, 6, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 9, 7, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 20, 8, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 4, 9, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 8, 10, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 5, 11, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 6, 12, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 5, 13, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 1, 14, 1)",
                    "INSERT INTO " + schema + ".VIDEOGAME_SHOP VALUES (NEXT VALUE FOR SHOP_VIDEOGAME_GEN, 1, 15, 1)"

                              
            };

            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
